spring.application.name=MQA-pdf-generator

# PostgreSQL Datasource Configuration
spring.datasource.url=jdbc:postgresql://ep-lingering-meadow-aovdqoy9-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_v0gbLSGo5RrH
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configurations
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# MQA PDF Generation Properties
pdf.logo.path=/static/images/logo.png
pdf.watermark.text=MQA SECURE
pdf.brand.color=#2c3e50

